---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: acmeair-auth-route-mc1
spec:
  host: acmeair.apps.api.acm213-manage.cp.fyre.ibm.com
  path: /auth
  to:
    kind: Service
    name: acmeair-auth-service
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: acmeair-auth-route-mc2
spec:
  host: acmeair.apps.api.acm213-manage.cp.fyre.ibm.com
  path: /auth
  to:
    kind: Service
    name: acmeair-auth-service
