---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: acmeair-customer-route-mc1
spec:
  host: acmeair.apps.m4205001.lnxero1.boe
  path: /customer
  to:
    kind: Service
    name: acmeair-customer-service
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: acmeair-customer-route-mc2
spec:
  host: acmeair.apps.m4202001.lnxero1.boe
  path: /customer
  to:
    kind: Service
    name: acmeair-customer-service
