---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: acmeair-main-route-mc1
spec:
  host: acmeair.apps.api.a3e20008-f1.cp.fyre.ibm.com
  path: /acmeair
  to:
    kind: Service
    name: acmeair-main-service
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: acmeair-main-route-mc2
spec:
  host: acmeair.apps.m4204001-f2.cp.fyre.ibm.com
  path: /acmeair
  to:
    kind: Service
    name: acmeair-main-service
